---
name: RankSystem
author: IvanCraft623
website: https://github.com/IvanCraft623/RankSystem
version: 0.0.2
main: IvanCraft623\RankSystem\RankSystem
api: 3.0.0
permissions:
  ranksystem.commands:
    default: op
    description: "Allows use ranks commands"
...
