---
name: Ranks
author: IvanCraft623
version: 0.0.1
main: IvanCraft623\RankSystem\RankSystem
api: 4.0.0
permissions:
  ranksystem.commands:
    default: op
    description: "Allows use ranks commands"
...
